### ISSUE TITLE
sublime text 3 loading plugin syntax error in sublime_plugin.py line 73

### ISSUE THREAD

**Issue by bcowgill** [jonschlinkert/sublime-grunt-build#7]
sublime text 3 ubuntu loading plugin syntax error in sublime_plugin.py line 73
Ubuntu 12.04.2 LTS \n \l
python --version
Python 2.7.3

reloading plugin sublime-grunt-build.grunt-build-on-save
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 854, in _load_module
  File "<frozen importlib._bootstrap>", line 981, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/brent.cowgill/.config/sublime-text-3/Packages/sublime-grunt-build/grunt-build-on-save.py", line 6
    print 'BuildGruntOnSave: on_post_save'

I changed the two print statements locally to     print ('BuildGruntOnSave: on_post_save') to correct this but i'm no python programmer so not sure if this is best fix for compatability with older sublime.

**Comment by jonschlinkert** [comment]
thanks, I'll look into it
